/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author A455L
 */
public class Level2b extends javax.swing.JFrame {

    /**
     * Creates new form Level2b
     */
    public Level2b() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lim = new javax.swing.JTextField();
        empa = new javax.swing.JTextField();
        ena = new javax.swing.JTextField();
        tuju = new javax.swing.JTextField();
        delapa = new javax.swing.JTextField();
        sembila = new javax.swing.JTextField();
        sat = new javax.swing.JTextField();
        tig = new javax.swing.JTextField();
        du = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\bahan pbo\\n.png")); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(590, 0, 50, 90);

        lim.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        lim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lim.setBorder(null);
        getContentPane().add(lim);
        lim.setBounds(140, 160, 70, 60);

        empa.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        empa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        empa.setBorder(null);
        getContentPane().add(empa);
        empa.setBounds(50, 160, 70, 60);

        ena.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        ena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ena.setBorder(null);
        ena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enaActionPerformed(evt);
            }
        });
        getContentPane().add(ena);
        ena.setBounds(240, 160, 70, 60);

        tuju.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        tuju.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tuju.setBorder(null);
        getContentPane().add(tuju);
        tuju.setBounds(340, 160, 70, 60);

        delapa.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        delapa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        delapa.setBorder(null);
        getContentPane().add(delapa);
        delapa.setBounds(430, 160, 70, 60);

        sembila.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        sembila.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sembila.setBorder(null);
        getContentPane().add(sembila);
        sembila.setBounds(530, 160, 70, 60);

        sat.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        sat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sat.setBorder(null);
        getContentPane().add(sat);
        sat.setBounds(200, 70, 60, 50);

        tig.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        tig.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tig.setBorder(null);
        getContentPane().add(tig);
        tig.setBounds(390, 70, 60, 50);

        du.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        du.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        du.setBorder(null);
        getContentPane().add(du);
        du.setBounds(290, 70, 60, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\bahan pbo\\SSSSSSSSSSSSSSSS.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 646, 470);

        setSize(new java.awt.Dimension(659, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enaActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
           if (sat.getText().equals("P") && du.getText().equals("A") && tig.getText().equals("K")&& empa.getText().equals("A")&& lim.getText().equals("R")&& ena.getText().equals("I")&& tuju.getText().equals("F")&& delapa.getText().equals("I")&& sembila.getText().equals("N")){
            JOptionPane.showMessageDialog(null, "MASUK KE LEVEL 3");
               new Level3().setVisible(true);
           dispose();
            JOptionPane.showMessageDialog(null, "Pakai huruf kapital ya:)");
        }else {
            JOptionPane.showMessageDialog(null, "ulang lagi");
            sat.setText("");
            du.setText("");
            tig.setText("");
            empa.setText("");
            lim.setText("");
            ena.setText("");
           tuju.setText("");
           delapa.setText("");
           sembila.setText("");
           }

        
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level2b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level2b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level2b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level2b.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level2b().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField delapa;
    private javax.swing.JTextField du;
    private javax.swing.JTextField empa;
    private javax.swing.JTextField ena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField lim;
    private javax.swing.JTextField sat;
    private javax.swing.JTextField sembila;
    private javax.swing.JTextField tig;
    private javax.swing.JTextField tuju;
    // End of variables declaration//GEN-END:variables
}
