/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author A455L
 */
public class Level2a extends javax.swing.JFrame {

    /**
     * Creates new form Level2a
     */
    public Level2a() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        E = new javax.swing.JTextField();
        L = new javax.swing.JTextField();
        N = new javax.swing.JTextField();
        S = new javax.swing.JTextField();
        SE = new javax.swing.JTextField();
        U = new javax.swing.JTextField();
        D = new javax.swing.JTextField();
        T = new javax.swing.JTextField();
        A = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/next.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 0, 190, 50);

        E.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        E.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        E.setBorder(null);
        getContentPane().add(E);
        E.setBounds(50, 170, 70, 50);

        L.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        L.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        L.setBorder(null);
        getContentPane().add(L);
        L.setBounds(150, 170, 60, 50);

        N.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        N.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        N.setBorder(null);
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });
        getContentPane().add(N);
        N.setBounds(240, 170, 70, 50);

        S.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        S.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        S.setBorder(null);
        getContentPane().add(S);
        S.setBounds(190, 70, 70, 60);

        SE.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        SE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SE.setBorder(null);
        getContentPane().add(SE);
        SE.setBounds(530, 170, 70, 50);

        U.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        U.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        U.setBorder(null);
        getContentPane().add(U);
        U.setBounds(340, 170, 60, 50);

        D.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        D.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        D.setBorder(null);
        getContentPane().add(D);
        D.setBounds(290, 70, 70, 60);

        T.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        T.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        T.setBorder(null);
        getContentPane().add(T);
        T.setBounds(390, 70, 70, 60);

        A.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        A.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        A.setBorder(null);
        getContentPane().add(A);
        A.setBounds(430, 170, 70, 50);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 260, 670, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/SSSSSSSSSSSSSSSS.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 480);

        setSize(new java.awt.Dimension(662, 515));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (S.getText().equals("P") && D.getText().equals("A") && T.getText().equals("K")&& E.getText().equals("A")&& L.getText().equals("R")&& N.getText().equals("I")&& U.getText().equals("F")&& A.getText().equals("I")&& SE.getText().equals("N")){
            JOptionPane.showMessageDialog(null, "LEVEL 3");
        new Level3().setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(null, "Pakai huruf kapital ya:)");
        }else {
            JOptionPane.showMessageDialog(null, "ulang lagi");
            S.setText("");
            D.setText("");
            T.setText("");
            E.setText("");
            L.setText("");
            N.setText("");
            U.setText("");
            A.setText("");
            SE.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level2a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level2a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level2a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level2a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level2a().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField D;
    private javax.swing.JTextField E;
    private javax.swing.JTextField L;
    private javax.swing.JTextField N;
    private javax.swing.JTextField S;
    private javax.swing.JTextField SE;
    private javax.swing.JTextField T;
    private javax.swing.JTextField U;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
