/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author A455L
 */
public class Level2a extends javax.swing.JFrame {

    /**
     * Creates new form Level2a
     */
    public Level2a() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        SATU = new javax.swing.JTextField();
        DUA = new javax.swing.JTextField();
        TIGA = new javax.swing.JTextField();
        EMPAT = new javax.swing.JTextField();
        LIMA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\bahan pbo\\btn.png")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 10, 300, 60);

        SATU.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        SATU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SATU.setBorder(null);
        getContentPane().add(SATU);
        SATU.setBounds(40, 130, 80, 60);

        DUA.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        DUA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DUA.setBorder(null);
        getContentPane().add(DUA);
        DUA.setBounds(160, 130, 80, 60);

        TIGA.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        TIGA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TIGA.setBorder(null);
        TIGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIGAActionPerformed(evt);
            }
        });
        getContentPane().add(TIGA);
        TIGA.setBounds(280, 130, 80, 60);

        EMPAT.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        EMPAT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EMPAT.setBorder(null);
        getContentPane().add(EMPAT);
        EMPAT.setBounds(400, 130, 90, 60);

        LIMA.setFont(new java.awt.Font("Tekton Pro", 1, 24)); // NOI18N
        LIMA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LIMA.setBorder(null);
        getContentPane().add(LIMA);
        LIMA.setBounds(520, 130, 90, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\bahan pbo\\assddd.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 260, 670, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\bahan pbo\\lv21.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 480);

        setSize(new java.awt.Dimension(662, 515));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (SATU.getText().equals("L") && DUA.getText().equals("A") && TIGA.getText().equals("R")&& EMPAT.getText().equals("S")&& LIMA.getText().equals("O")){
            new Level2b().setVisible(true);
            dispose();
        }else {
            JOptionPane.showMessageDialog(null, "ulang lagi");
            SATU.setText("");
            DUA.setText("");
            TIGA.setText("");
            EMPAT.setText("");
            LIMA.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void TIGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIGAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIGAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level2a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level2a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level2a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level2a.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level2a().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DUA;
    private javax.swing.JTextField EMPAT;
    private javax.swing.JTextField LIMA;
    private javax.swing.JTextField SATU;
    private javax.swing.JTextField TIGA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
