/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author A455L
 */
public class Level2 extends javax.swing.JFrame {

    /**
     * Creates new form Level2
     */
    public Level2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiga = new javax.swing.JTextField();
        dua = new javax.swing.JTextField();
        satu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SJSAKJSSA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tiga.setFont(new java.awt.Font("Minion Pro", 1, 24)); // NOI18N
        tiga.setForeground(new java.awt.Color(255, 153, 0));
        tiga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tiga.setBorder(null);
        tiga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tiga.setSelectedTextColor(new java.awt.Color(255, 204, 204));
        tiga.setSelectionColor(new java.awt.Color(255, 204, 204));
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        getContentPane().add(tiga);
        tiga.setBounds(420, 120, 120, 60);

        dua.setFont(new java.awt.Font("Minion Pro", 1, 24)); // NOI18N
        dua.setForeground(new java.awt.Color(255, 153, 0));
        dua.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dua.setBorder(null);
        dua.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dua.setSelectedTextColor(new java.awt.Color(255, 204, 204));
        dua.setSelectionColor(new java.awt.Color(255, 204, 204));
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        getContentPane().add(dua);
        dua.setBounds(260, 120, 120, 60);

        satu.setFont(new java.awt.Font("Minion Pro", 1, 24)); // NOI18N
        satu.setForeground(new java.awt.Color(255, 153, 0));
        satu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        satu.setBorder(null);
        satu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        satu.setSelectedTextColor(new java.awt.Color(255, 204, 204));
        satu.setSelectionColor(new java.awt.Color(255, 204, 204));
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        getContentPane().add(satu);
        satu.setBounds(110, 120, 120, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\bahan pbo\\btn.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 300, 60);

        SJSAKJSSA.setIcon(new javax.swing.ImageIcon("D:\\bahan pbo\\lv2.png")); // NOI18N
        getContentPane().add(SJSAKJSSA);
        SJSAKJSSA.setBounds(0, 0, 650, 470);

        setSize(new java.awt.Dimension(660, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duaActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_satuActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tigaActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
  if (satu.getText().equals("A") && dua.getText().equals("D") && tiga.getText().equals("I")){
                new Level2a().setVisible(true);
                dispose();
            }else {
                  JOptionPane.showMessageDialog(null, "ulang lagi");
                  satu.setText("");
                  dua.setText("");
                  tiga.setText("");
            }

                
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Level2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Level2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SJSAKJSSA;
    private javax.swing.JTextField dua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField satu;
    private javax.swing.JTextField tiga;
    // End of variables declaration//GEN-END:variables
}
